import { Brain, Ear, Eye, Flower2, Hand, Utensils } from "lucide-react";
import type { Sense } from "../types/content";
import { goutArticles, makeArticles } from "./staticArticles";

export const senses: Sense[] = [
  {
    id: "vue",
    slug: "vue",
    label: "Vue",
    senseNumber: "01",
    intro: "Explorer la lumière, les formes et les images qui restent.",
    homeText: "La lumière pose une émotion avant les mots.",
    homeImage:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=90",
    icon: Eye,
    articles: makeArticles([
      "La ligne d'horizon",
      "Blancs méditerranéens",
      "Ombres sur la pierre",
      "Le bleu après midi",
      "Fenêtres ouvertes",
      "La peau des murs",
      "Jardins silencieux",
      "L'éclat du verre",
    ]),
  },
  {
    id: "ouie",
    slug: "ouie",
    label: "Ouïe",
    senseNumber: "02",
    intro: "Explorer les sons discrets, les silences et les résonances.",
    homeText: "Un son suffit parfois à rouvrir une saison.",
    homeImage:
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1800&q=90",
    icon: Ear,
    articles: makeArticles([
      "Le souffle du matin",
      "Une cloche au loin",
      "Vinyle et poussière",
      "Le silence des chambres",
      "Voix basses",
      "L'eau contre la pierre",
      "Notes de terrasse",
      "La mer en sourdine",
    ]),
  },
  {
    id: "odorat",
    slug: "odorat",
    label: "Odorat",
    senseNumber: "03",
    intro: "Explorer les traces invisibles et les mémoires parfumées.",
    homeText: "Une trace invisible, et la mémoire devient paysage.",
    homeImage:
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1800&q=90",
    icon: Flower2,
    articles: makeArticles([
      "Figue chaude",
      "Linge au soleil",
      "Mémoire des résines",
      "Basilic froissé",
      "La pluie sur la terre",
      "Bois blond",
      "Peau salée",
      "Rose ancienne",
    ]),
  },
  {
    id: "gout",
    slug: "gout",
    label: "Goût",
    senseNumber: "04",
    intro: "Explorer ce qui donne du goût à la vie.",
    homeText: "Le vivant se raconte dans une nuance brève.",
    homeImage: "/images/gout.avif",
    icon: Utensils,
    articles: goutArticles,
  },
  {
    id: "toucher",
    slug: "toucher",
    label: "Toucher",
    senseNumber: "05",
    intro: "Explorer les matières, les peaux et les textures calmes.",
    homeText: "La matière calme le regard et réveille la présence.",
    homeImage:
      "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=90",
    icon: Hand,
    articles: makeArticles([
      "Lin froissé",
      "Marbre tiède",
      "Céramique mate",
      "La main sur le bois",
      "Coton épais",
      "Pierre polie",
      "Peau et lumière",
      "Le grain du papier",
    ]),
  },
  {
    id: "esprit",
    slug: "esprit",
    label: "Esprit",
    senseNumber: "06",
    intro: "Explorer l'intuition, les souvenirs et les liens invisibles.",
    homeText: "L'intuition relie ce que les sens ont commencé.",
    homeImage:
      "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1800&q=90",
    icon: Brain,
    articles: makeArticles([
      "La mémoire des lieux",
      "Rituels minuscules",
      "Une idée claire",
      "Présences lentes",
      "Le rêve du dimanche",
      "Carnets ouverts",
      "L'intuition du geste",
      "Ce qui revient",
    ]),
  },
];
